### ISSUE TITLE
启动应用时报错

### ISSUE THREAD

**Issue by usydapeng** [turingou/candy#52]
使用 `PORT=3001 node app.js`启动时报错
···
/opt/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:367
    throw new Error(msg);
          ^
Error: Router.use() requires callback functions but got a [object Error]
    at Function.proto.use (/opt/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:367:11)
    at Function.app.use (/opt/candy/node_modules/express-scaffold/node_modules/express/lib/application.js:199:16)
    at new Server (/opt/candy/node_modules/express-scaffold/libs/server.js:95:7)
    at Object.<anonymous> (/opt/candy/app.js:18:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
···

**Comment by lpn520** [comment]
我也是
