### ISSUE TITLE
Candy 现在基本瘫痪跑不起来了

### ISSUE THREAD

**Issue by Minwe** [turingou/candy#54]
从 GitHub 中克隆的代码，运行的时候遇到以下问题。

## 第一个问题是由 `express-scaffold` 引起的

`express-scaffold` 依赖的的 `node-sass` 没有指定版本号，最新版的 `node-sass` 已经把 middleware 独立到另外一个模块中，导致启动的时候报错。找到 `express-scaffold` 目录下面的 `libs/server.js`，把 `95` 行注销了，可以启动服务了。

```js
// app.use(sass({ src: dirs.publics }));
```

## 多说账号登录问题

接下来使用第三方账号登录，结果又报下面的错……

```
[Error: code is required]
Error: code is required
    at Duoshuo.auth (/Users/minwe/Downloads/candy/node_modules/duoshuo/libs/duoshuo.js:21:30)
    at Object.handle (/Users/minwe/Downloads/candy/node_modules/duoshuo/libs/duoshuo.js:40:10)
    at next_layer (/Users/minwe/Downloads/candy/node_modules/express-scaffold/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/Users/minwe/Downloads/candy/node_modules/express-scaffold/node_modules/express/lib/router/route.js:107:5)
    at /Users/minwe/Downloads/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:213:24
    at Function.proto.process_params (/Users/minwe/Downloads/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:284:12)
    at next (/Users/minwe/Downloads/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:207:19)
    at next (/Users/minwe/Downloads/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:182:38)
    at Function.proto.handle (/Users/minwe/Downloads/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:154:3)
    at Layer.router (/Users/minwe/Downloads/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:24:12)
```

**Comment by turingou** [comment]
请在生产环境中使用 npm 中的稳定版本~ master 分支上的代码仍在不断变化中

**Comment by Minwe** [comment]
好，再试试 NPM 上的版本。谢谢。
