### ISSUE TITLE
登录时出错.

### ISSUE THREAD

**Issue by bshy522** [turingou/candy#55]
提示说code是必选参数? 

同时首页获取文章列表也都报错了.

**Comment by turingou** [comment]
是使用 master 分支的代码跑的吗?

**Comment by bshy522** [comment]
是的.

**Comment by bshy522** [comment]
7457bc9cdbaed71a06b17fd1b2c97f2af3bd05bc 用的这个提交.

**Comment by bshy522** [comment]
还有一个bug,  'express-scaffold' 里面的'sass'中间件报错, 应该是sass模块更新了的原因.

**Comment by turingou** [comment]
master 分支中的代码尚在重构中，可以使用 npm 中的稳定版本试试看

**Comment by bshy522** [comment]
好的 我试试.

**Comment by bshy522** [comment]
``
{ [Error: Failed to lookup view "error"]
  view:
   { name: 'error',
     root: '/Users/larry/candy-demo/node_modules/candy/node_modules/candy-theme-flat',
     defaultEngine: 'jade',
     ext: '.jade',
     engine: [Function],
     path: undefined } }
Error: Failed to lookup view "error"
    at Function.app.render (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/lib/application.js:494:17)
    at ServerResponse.res.render (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/lib/response.js:756:7)
    at Object.exports.render (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/middlewares/error.js:11:14)
    at Object.res.format.html (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/middlewares/error.js:41:22)
    at ServerResponse.res.format (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/lib/response.js:466:13)
    at exports.notfound (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/middlewares/error.js:35:14)
    at callbacks (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:161:37)
    at param (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:135:11)
    at pass (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:142:5)
    at nextRoute (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/lib/router/index.js:100:7)
Error: Failed to lookup view "error"
    at Function.app.render (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/lib/application.js:494:17)
    at ServerResponse.res.render (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/lib/response.js:756:7)
    at Object.exports.render (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/middlewares/error.js:11:14)
    at Object.exports.common [as handle] (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/middlewares/error.js:31:18)
    at next (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/node_modules/connect/lib/proto.js:185:17)
    at Object.exports.xhr [as handle] (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/middlewares/error.js:26:10)
    at next (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/node_modules/connect/lib/proto.js:185:17)
    at Object.exports.logger [as handle] (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/middlewares/error.js:20:10)
    at IncomingMessage.next (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/node_modules/connect/lib/proto.js:185:17)
    at fn (/Users/larry/candy-demo/node_modules/candy/node_modules/express-scaffold/node_modules/express/lib/response.js:751:25)
``

1.7版本 出这个错...

**Comment by turingou** [comment]
估计是 candy-theme-flat 的版本没有固定住，在这之后 candy-theme-flat 的 error.jade 被拆分成了 404.jade 和 500.jade，你现在本地的 candy-theme-flat 版本是？

**Comment by bshy522** [comment]
0.1,  我自己改一下就行了么?

**Comment by bshy522** [comment]
我把theme换到了0.0.3 也不行~ 页面js依赖都没有了.

然后我尝试点了下登录  会有这个错误 ``Error: code required``

**Comment by turingou** [comment]
这周末我解决一下 candy 的问题吧~ 不好意思，最近比较忙，没时间贡献代码

**Comment by bshy522** [comment]
哦哦, 好的, 辛苦了. 感谢.

**Comment by bshy522** [comment]
这个错是因为多说的那个模块版本不对造成的么?
