### ISSUE TITLE
两种方法安装都会报错。。。

### ISSUE THREAD

**Issue by Mess1ah** [turingou/candy#56]
第一种报js的错，第二种报Cannot find module 'npm'

**Comment by Collin-V** [comment]
我这也是这个问题
module.js:340
    throw err;
          ^
Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/candy/node_modules/candy/node_modules/theme/node_modules/pkghub/libs/npm.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
